// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExtHandler is an autogenerated mock type for the ExtHandler type
type ExtHandler struct {
	mock.Mock
}

// ValidateToken provides a mock function with given fields: token
func (_m *ExtHandler) ValidateToken(token string) error {
	ret := _m.Called(token)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
